spring:
  config:
    import: file:env.yml
  application:
    name: BookReader
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}

cloudinary:
  name: ${CLOUDINARY_CLOUD_NAME}
  key: ${CLOUDINARY_API_KEY}
  secret: ${CLOUDINARY_API_SECRET}